config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'
  match '/reserved' => 'application#reserved', via: :get
  match '/reserved' => 'application#reserved', via: :post
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'application'
  @status = ""
  # default route
  def index
      @status = ""
      render template: 'index/index.html.erb'
      #render html: 'olá'
  end
  
  def reserved
    if params
      @status = "Reservado"
    else
      @status = ""
    end
    render template: 'index/index.html.erb'
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/index/index.html.erb
Escolha seu minion:<br />
<%= form_tag(reserved_path, :method => :post) do %>
    <%= radio_button_tag 'minion', 'Kevin', :id => 'kevin', :required => true %> <%= image_tag("kevin.png", :alt => "kevin", :class => "minions") %>
    <%= radio_button_tag 'minion', 'bob', :id => 'bob', :class => 'bob' %> <%= image_tag("bob.png", :alt => "bob", :class => "minions bob") %>
    <%= radio_button_tag 'minion', 'stuart', :id => 'stuart', :class => 'stuart' %> <%= image_tag("stuart.png", :alt => "stuart", :class => "minions stuart") %>
    
    <%= label_tag 'name', 'Nome:' %> <%= text_field_tag 'name', nil, placeholder: 'Seu nome completo', :required => true %> 
    <%= label_tag 'email', 'Email:' %> <%= email_field_tag 'email', nil, placeholder: 'seu@email.com', :required => true %> 
    <%= label_tag 'address', 'Endereço:' %><%= text_field_tag 'address', nil, placeholder: 'Seu endereço', :required => true %> 
    <div id="button_submit"><%= submit_tag("Reservar Minion!")  %></div>
<% end %>
<%= @status  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    </head>
    <body>
        <header><div id="header_image">
            <img id="minions_header" src="https://thumbor.forbes.com/thumbor/1280x868/https%3A%2F%2Fblogs-images.forbes.com%2Fmarkhughes%2Ffiles%2F2015%2F08%2FMINIONS-2.png">
            </div>
            <h1 id="title">Reserve aqui seu minion!</h1>
            </header>
        <div id="body">
            <div id="minions_desc">
                <article>Os minions já invadiram quase o mundo inteiro, agora falta sua casa e seu coração.</article>
                <img src="https://vignette.wikia.nocookie.net/tayothelittlebus/images/9/97/Bob_minions_2015.png/revision/latest?cb=20150807182137">
            </div>
            <div id="minions_order"> <%= yield -%> </div>
        </div>
        <footer></footer>
    </body>
</html>